#!/hint/bash

WINE="umu-run"
PREFIX_VAR_NAME="WINEPREFIX"

# Use proton-cachyos-slr by default
#PROTONPATH="/path/to/proton/"
[ -z "$PROTONPATH" ] && PROTONPATH="/usr/share/steam/compatibilitytools.d/proton-cachyos-slr/"
