# 通用配置

# 性能监测覆盖层
mangohud.enabled = true

# 游戏模式 (使用 wrapper 加载 和后者冲突)
gamemode.wrapper.enabled = true
# 游戏模式 (使用 LD_PRELOAD 加载 和前者冲突)
#gamemode.ld_preload.enabled = true

# 创建一个 pfx -> . 的链接，umu 应该自带了
#features.pfx_link = true

# 游戏运行前杀死 wineserver
prepare.kill_wineserver = true
# 读取 Intel RAPL 能耗数据
prepare.intel_rapl_read = true

# 两个缓存
#cache.shader.enabled = true
#cache.dx.enabled = true

# CPU 亲和性设置
#taskset.enabled = true
#taskset.cpus = [ 0, 2, 4, 6, 8, 10, 12, 14 ]
#taskset.cpus = [ 0-7, 8-15 ]

# 部分游戏支持 将用户数据链接 方便管理
#features.userdata_link.enabled = true
# 截图数据，默认 `$(xdg-user-dir PICTURES)/HypsScreenshots`，每个游戏还有一层子文件夹在里面
#features.userdata_link.screenshots = "/path/to/your/Screenshots"

# NVIDIA DLSS
# 也可以放在游戏单独的配置里
# 这里列出一些常用的
# nvapi.drs.settings = [
    # "ngx_dlss_sr_override_render_preset_selection=render_preset_m", # 超分辨率 预设
    # "ngx_dlss_fg_override_render_preset_selection=render_preset_b", # 帧生成 预设
# ]
# DLSS 指示器
# 开启后会显示 DLSS 版本、使用的预设 (Render Preset) 和一些别的信息
# 左下角显示超分辨率信息 左上角显示帧生成信息
#env.PROTON_DLSS_INDICATOR = true

# 编译用 C 写的小工具的编译选项
env.CFLAGS = [
    # 我都是为你好 😡
    "-Wall", "-Wextra",
    # 就一些小工具 有必要这么做吗 🤔
    #"-O3", "-march=native",
]
