# 通用配置

# 性能监测覆盖层
mangohud.enabled = true
# 游戏模式
gamemode.enabled = true

# 创建一个 pfx -> . 的链接，umu 应该自带了
#features.pfx_link = true

# 游戏运行前杀死 wineserver
prepare.kill_wineserver = true
# 读取 Intel RAPL 能耗数据
prepare.intel_rapl_read = true

# 两个缓存
#cache.shader.enabled = true
#cache.dx.enabled = true

# CPU 亲和性设置
#taskset.enabled = true
#taskset.cpus = [ 0, 2, 4, 6, 8, 10, 12, 14 ]
#taskset.cpus = [ 0-7, 8-15 ]
