game.exe = "/path/to/Endfield Game/Endfield.exe"

# 需要 dwproton 10.0-13 及以上版本，或 proton-ge 10-31 及以上版本
# 推荐 dwproton 11.0-9 及以上版本
runner.name = "umu-dwproton"

# 推荐 NVIDIA 显卡驱动 615.78.08 及以上版本
# 如遇 DLSS 帧生成卡死问题，尝试更换 Proton 和显卡驱动版本，已知 dwproton & 615.71.09 会导致问题
# 驱动版本在 615.71.09 (不包含) 以下时，NVIDIA Reflex 需要额外配置 VK_LAYER_DXVK_NVAPI_reflex 层

# 游戏参数
game.args = [
    # "-force-d3d11", # 如果需要 D3D11 启动游戏，可以取消其注释
    # "-force-vulkan", # 默认是 Vulkan，通常不需要强制指定
]
