game.exe = "/path/to/Endfield Game/Endfield.exe"

# 需要 dwproton 10.0-13 及以上版本，或 proton-ge 10-31 及以上版本
# 推荐 dwproton 11.0-9 及以上版本
runner.name = "umu-dwproton"

# NVIDIA Reflex 低延迟
# 需要先安装 VK_LAYER_DXVK_NVAPI_reflex 层
# Arch Linux 用户可通过 AUR 安装 dxvk-nvapi-vkreflex-layer 包
# 参见 https://docs.nvidia.com/datacenter/tesla/driver-installation-guide/gaming.html#reflex-for-vulkan-steam-play-proton
#nvapi.vkreflex = true
