game.exe = "/path/to/Endfield Game/Endfield.exe"

# 需要 dwproton 10.0-13 及以上版本，或 proton-ge 10-31 及以上版本
# 推荐 dwproton 11.0-9 及以上版本
runner.name = "umu-dwproton"

# 游戏参数
game.args = [
    # "-force-d3d11", # 如果需要 DX11 启动游戏，可以取消其注释
    # "-force-vulkan", # 默认是 Vulkan，通常不需要强制指定
]

# NVIDIA Reflex 低延迟
# 需要先安装 VK_LAYER_DXVK_NVAPI_reflex 层
# Arch Linux 用户可通过 AUR 安装 dxvk-nvapi-vkreflex-layer 包
# 参见 https://docs.nvidia.com/datacenter/tesla/driver-installation-guide/gaming.html#reflex-for-vulkan-steam-play-proton
#nvapi.vkreflex = true
