#!/hint/bash
#shellcheck disable=2034



# 选用的运行器, 在 `../Runners/$RUNNER.conf` 中定义
RUNNER="umu-dwproton"
# 选择的前缀, 不填写则由运行器选择
#PREFIX="/path/to/prefix"

# 游戏本体路径
GAME="/path/to/Honkai Impact 3rd Game/BH3.exe"

# 神秘小参数
UMU_USE_STEAM="y"
