#!/hint/bash
#shellcheck disable=2034

# === dwproton 11.0-10 及以上版本才能运行 === #



# 选用的运行器, 在 `../Runners/$RUNNER.conf` 中定义
RUNNER="umu-dwproton"
# 选择的前缀, 不填写则由运行器选择
#PREFIX="/path/to/prefix"

# 游戏本体路径
GAME="/path/to/Star Rail Game/StarRail.exe"



# 注册表解锁帧率
# 可能需要启动游戏后，也可能需要手动更改一下游戏内设置（创建注册表项），第二次启动时生效
#STARRAIL_REG_FPS="y"
# 目标帧率, 默认为 120
STARRAIL_REG_FPS_VAL="120"
