game.exe = "/path/to/Star Rail Game/StarRail.exe"

# 需要 dwproton 11.0-10 及以上版本
runner.name = "umu-dwproton"

# 注册表解锁帧率
# 可能需要启动游戏后，也可能需要手动更改一下游戏内设置（创建注册表项），第二次启动时生效
#starrail.reg_fps.enabled = true
#starrail.reg_fps.val = 120
