game.exe = "/path/to/Wuthering Waves Game/Client/Binaries/Win64/Client-Win64-Shipping.exe"

# 需要 proton-ge 10-25 及以上版本
# 推荐 dwproton 11.0-12 及以上版本
runner.name = "umu-dwproton"

# 推荐 NVIDIA 显卡驱动 610.57.04 及以上版本

# 游戏参数
game.args = [
    # "-dx11", # 如果需要 DX11 启动游戏，可以取消其注释
    # "-dx12", # 默认是 DX12，如果还是 DX11 可以试试强制指定
    # "-SkipSplash", # 跳过开场动画 (Kuro Games 和光敏性癫痫警告的那一段)
    # "-ForceEnableCSharpEnvironment", # 强制启用 C# 环境 (实验性) [游戏版本 v3.6.0 留]
]

# 开启 DX12 后，让 VKD3D 启用 descriptor_heap 以提高翻译效率
# 需要支持 VK_EXT_descriptor_heap，且**极大概率会导致崩溃**
#env.VKD3D_CONFIG="descriptor_heap"
