game.exe = "/path/to/Wuthering Waves Game/Client/Binaries/Win64/Client-Win64-Shipping.exe"

# 需要 proton-ge 10-25 及以上版本
# 推荐 dwproton 11.0-5 及以上版本
runner.name = "umu-dwproton"

# 推荐 NVIDIA 显卡驱动 610.57.04 及以上版本

# 游戏参数
# 如果需要 DX11 启动游戏，可以取消其注释
#game.args = [ "-dx11" ]

# 开启 DX12 后，让 VKD3D 启用 descriptor_heap 以提高翻译效率
# 需要支持 VK_EXT_descriptor_heap，且可能会导致崩溃
#env.VKD3D_CONFIG="descriptor_heap"
