#!/hint/bash
#shellcheck disable=2034



# 选用的运行器, 在 `../runners/$RUNNER.conf` 中定义
RUNNER="umu-dwproton"
# 选择的前缀, 默认在 `~/.local/share/hypsc/prefixes/$GAME_NAME` 下创建, 也可以自定义路径
#PREFIX="/path/to/prefix"

# 游戏本体路径
GAME="/path/to/Wuthering Waves Game/Client/Binaries/Win64/Client-Win64-Shipping.exe"

# 游戏参数
# 如果需要 dx11 启动游戏，可以取消其注释
#GAME_ARGS="-dx11"

# 开启 DX12 后，让 VKD3D 启用 descriptor_heap 以提高翻译效率
# 需要支持 VK_EXT_descriptor_heap，且可能会导致崩溃
#VKD3D_CONFIG="descriptor_heap"
