game.exe = "/path/to/Genshin Impact Game/YuanShen.exe"

# 需要 dwproton 11.0-2 及以上版本
runner.name = "umu-dwproton"

# 应该会自动检测到 如果游戏打不开就来开
#env.GAMEID = "umu-genshin"

# 帧率解锁
#gi.fps_unlock.enabled = true
#gi.fps_unlock.val = 120
#gi.fps_unlock.sleep = 10 # 如果不设置就是调用 xwin-watch，需要设置窗口名称
#xwin_watch.window_name = "原神"

# 注册表 HDR
#gi.reg_hdr.enabled = true
# 注意还要确保本机和 proton 的 HDR 可用
#env.PROTON_ENABLE_WAYLAND = true
#env.PROTON_ENAbLE_HDR = true
#env.DXVK_HDR = true
