#!/hint/bash
#shellcheck disable=2034

# === 已不受支持 ===
# 目前能用，但不保证未来能用，方案多变



# 选用的运行器, 在 `../Runners/$RUNNER.conf` 中定义
RUNNER="umu-dwproton"
# 选择的前缀, 不填写则由运行器选择
#PREFIX="/path/to/prefix"

# 游戏本体路径
GAME="/path/to/Genshin Impact Game/YuanShen.exe"



# 神秘小参数
UMU_USE_STEAM="y"



# 使用 FPS Unlock
#FPS_UNLOCK="y"
# FPS Unlock 的目标帧速率, 默认为 240
FPS_UNLOCK_FPS="240"
# FPS Unlock 定期写入的延迟 (毫秒), 默认为 5000
FPS_UNLOCK_INTERVAL="5000"
# FPS Unlock 等待游戏启动的秒数（不能和 FPS_UNLOCK_XWIN_WATCH 一起使用）
#FPS_UNLOCK_SLEEP="45"
# FPS Unlock 检测窗口等待游戏启动（不能和 FPS_UNLOCK_SLEEP 一起使用，需要填写窗口名称，且在 X11/Xwayland 上运行）
#FPS_UNLOCK_XWIN_WATCH="y"
# 监测游戏窗口
XWIN_WATCH_WINDOW="原神"
