game.exe = "/path/to/Genshin Impact Game/YuanShen.exe"

# 需要 dwproton 11.0-2 及以上版本
runner.name = "umu-dwproton"

# 应该会自动检测到 如果游戏打不开就来开
#env.GAMEID = "umu-genshin"

# 帧率解锁
# 警告: 游戏会定期向服务器报告测得的帧率，使用此工具风险自负
# 可使用以下命令热更新帧率限制 (将 120 替换为你想要的帧率)
# `echo 120 > /tmp/hypsc/fpsunlock_fifo`
# 特殊地，当目标帧率上限为 0 时为 dry run 模式，程序仅读取当前帧率上限并打印而不进行写入
# 反作弊严格的场景（幽境危战、千星奇域）可能会报错「检测到非法工具」10612-4001
# 游戏前关闭帧率解锁，或热更新帧率限制到合法范围内（个人测试的合法值为 120，可能有变动，最好 60）
#gi.fps_unlock.enabled = true
# 运行解帧时传入的目标帧率上限，可以被热更新
#gi.fps_unlock.val = 120
# 运行解帧的目标进程名称，默认为国服 "YuanShen.exe"，国际服为 "GenshinImpact.exe"
#gi.fps_unlock.prog = "YuanShen.exe"
# 游戏会在特定情况下（如切换场景时）重写帧率，解帧程序会每隔 <interval> 毫秒检查并修正帧率
#gi.fps_unlock.interval = 5000
# 运行解帧的等待时间，单位为秒；也可以不设置，使用 xwin-watch 检测窗口，需要设置窗口名称
#gi.fps_unlock.sleep = 10
#features.xwin_watch.window_name = "原神"
# xwin-watch 检测窗口的超时时间，单位为秒，默认 0 表示无限制
#features.xwin_watch.timeout = 0

# 注册表 HDR
#gi.reg_hdr.enabled = true
# 游戏注册表路径。默认值为国服，国际服需要将 "原神" 替换为 "Genshin Impact"
#gi.reg_hdr.path = "HKEY_CURRENT_USER\Software\miHoYo\原神"
# 注意还要确保本机和 proton 的 HDR 可用
#env.PROTON_ENABLE_WAYLAND = 1
#env.PROTON_ENABLE_HDR = 1
#env.DXVK_HDR = 1
