#!/hint/bash
#shellcheck disable=2034



# 选用的运行器, 在 `../runners/$RUNNER.conf` 中定义
RUNNER="umu-dwproton"
# 选择的前缀, 默认在 `~/.local/share/hypsc/prefixes/$GAME_NAME` 下创建, 也可以自定义路径
#PREFIX="/path/to/prefix"

# 游戏本体路径
GAME="/path/to/ZenlessZoneZero Game/ZenlessZoneZero.exe"

# 游戏参数
# `-use-d3d12` 可以使用 DX12，开放初期，优化较差，但有 DLSS 和光线追踪 [游戏版本 v3.0.0 留]
#GAME_ARGS="-use-d3d12"


# 开启 DX12 后，让 VKD3D 启用 descriptor_heap 以提高翻译效率
# 需要支持 VK_EXT_descriptor_heap，且可能会导致崩溃
#VKD3D_CONFIG="descriptor_heap"

# 神秘小参数
UMU_USE_STEAM="y"
