game.exe = "/path/to/ZenlessZoneZero Game/ZenlessZoneZero.exe"

# 需要 dwproton 11.0-2 及以上版本
runner.name = "umu-dwproton"

# 应该会自动检测到 如果游戏打不开就来开
#env.GAMEID = "umu-zenlesszonezero"

# 游戏参数
# `-use-d3d12` 可以使用 DX12，开放初期，优化较差，但有 DLSS 和光线追踪 [游戏版本 v3.0.0 留]
# game.args = [ "-use-d3d12" ]

# 开启 DX12 后，让 VKD3D 启用 descriptor_heap 以提高翻译效率
# 需要支持 VK_EXT_descriptor_heap，且可能会导致崩溃
#env.VKD3D_CONFIG="descriptor_heap"
