#!/hint/bash

[[ -n "${__UTILS_COMMAND_SH_LOADED:-}" ]] && return 0
__UTILS_COMMAND_SH_LOADED=1

command_exists() {
    command -v "$1" >/dev/null 2>&1
}

print_bash_script_header() {
    echo "#!/usr/bin/env bash"
    echo "# Auto-generated by Hyps"
    echo ""
}

pack_declare() {
    declare -p | grep -v '^declare -[a-zA-Z]*r'
    declare -f
}

ensure_executable() {
    local file="$1"
    local module="${2:-utils}"

    if [ ! -x "$file" ]; then
        chmod +x "$file"
    fi

    if [ ! -x "$file" ]; then
        die 1 "$module" "文件 '$file' 不可执行！请手动设置可执行权限！"
    fi
}
